# Generated by Django 4.0.6 on 2022-07-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
